apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: nginx
spec:
  scopes:
  - Cluster
  - Namespaced
  phases:
  - name: ns
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      type: object
      properties:
        addonsv1:
          type: object
          description: "contains configuration passed by Addon Operator"
          properties:
            parameters:
              type: object
              description: "Addon Parameters"
              x-kubernetes-preserve-unknown-fields: true
            clusterID:
              type: string
              description: "Cluster ID"
            deadMansSnitchUrl:
              type: string
              description: "Dead Man's Snitch URL"
            ocmClusterID:
              type: string
              description: "OCM Cluster ID"
            pagerDutyKey:
              type: string
              description: "PagerDuty API key"
            targetNamespace:
              type: string
              description: "Target Namespace"
          required:
            - parameters
            - clusterID
            - deadMansSnitchUrl
            - pagerDutyKey
            - targetNamespace
      required:
        - addonsv1
test:
  template:
  - name: namespace-n
    context:
      package:
        metadata:
          name: test-name
      config:
        addonsv1:
          clusterID: ABCD1234
          deadMansSnitchUrl: https://example.com/test-snitch-url
          ocmClusterID: EFGH5678
          pagerDutyKey: 1a2b3c4d5e6f
          parameters:
            param1: hey
            param2: 420
          targetNamespace: default
  - name: namespace-y
    context:
      package:
        metadata:
          name: test-name
          namespace: test-namespace
      config:
        addonsv1:
          clusterID: ABCD1234
          deadMansSnitchUrl: https://example.com/test-snitch-url
          ocmClusterID: EFGH5678
          pagerDutyKey: 1a2b3c4d5e6f
          parameters:
            param1: hey
            param2: 420
          targetNamespace: test-namespace